name: Build and Release for Windows, Linux and MacOS

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
          - target: x86_64-unknown-linux-gnu
            bin: pre-commit
            bin_name: pre-commit_upordawn
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            bin: pre-commit
            bin_name: pre-commit_upordawn
            os: macOS-latest
          - target: x86_64-pc-windows-gnu
            bin: pre-commit.exe
            bin_name: pre-commit_upordawn.exe
            os: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.platform.target }}
          override: true

      - name: Build
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--release"

      - name: Create target dir & Move binary
        run: |
          mkdir -p release_assets/${{ matrix.platform.os }}
          mv target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin_name }} release_assets/${{ matrix.platform.os }}/${{ matrix.platform.bin }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.token }}
          files: release_assets/${{ matrix.platform.os }}/${{ matrix.platform.bin }}
          body: |
            Release for ${{ matrix.platform.os }} target ${{ matrix.platform.target }}
          tag_name: ${{ matrix.platform.target }}
          draft: false
          prerelease: false
