name: Build and Release for Windows, Linux and MacOS

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-apple-darwin
          - x86_64-pc-windows-gnu

    steps:
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openssl libssl-dev pkg-config mingw-w64

      - name: Set up environment
        run: |
          export PATH="/usr/share/mingw-w64:$PATH"
          export PKG_CONFIG_PATH="/usr/lib/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig"
          export PKG_CONFIG_ALLOW_CROSS=1

      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          # args: --release
          args: --release --target=${{ matrix.target }}

      - name: Create target dir & Move binary
        run: |
          mkdir -p release_assets/${{ matrix.target }}
          mv target/release/pre-commit_upordawn release_assets/${{ matrix.target }}/pre-commit

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.token }}
          files: release_assets/${{ matrix.target }}/*
          body: |
            Release for ${{ matrix.target }}
          tag_name: ${{ matrix.target }}
          draft: false
          prerelease: false
