name: Build and Release for Windows, Linux and MacOS

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-apple-darwin
          - x86_64-pc-windows-gnu

    steps:
      - name: Install OpenSSL
        run: sudo apt-get install openssl

      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release
          # args: --release --target=${{ matrix.target }}
      
      - name: Set binary extension
        id: binary_extension
        run: |
          if [[ "${{ matrix.target }}" == "x86_64-pc-windows-gnu" ]]; then
            echo "::set-output name=binary_extension::.exe"
          else
            echo "::set-output name=binary_extension::"
          fi

      - name: Create target dir & Move binary
        run: |
          mkdir -p release_assets/${{ matrix.target }}
          mv target/${{ matrix.target }}/release/pre_commit release_assets/${{ matrix.target }}/pre-commit$($(echo ${{ steps.binary_extension.outputs.binary_extension }}))

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.token }}
          files: release_assets/${{ matrix.target }}/*
          body: |
            Release for ${{ matrix.target }}
          draft: false
          prerelease: false
