name: Build and Release for Windows, Linux and MacOS

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-apple-darwin
          - x86_64-pc-windows-gnu

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}

      - name: Create target dir & Move binary
        run: |
          mkdir ~/{{ matrix.target }}
          mv target/${{ matrix.target }}/release/pre-commit* ~/{{ matrix.target }}/

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.token }}
          files: |
            ~/${{ matrix.target }}
          body: |
            Release for ${{ matrix.target }}
          draft: false
          prerelease: false
