name: Testing pre-commit on every platform

on:
  push:
    branches:
      - '*test'

jobs:
  windows:
    runs-on: windows-latest
  
    steps:
      - name: Cloning UpOrDawn repo
        uses: actions/checkout@v4
        with:
          repository: Snoupix/UpOrDawn
          ref: master
          token: ${{ secrets.TOKEN }}
  
      - name: Install hook
        run: |
          npm i -g prettier eslint
          curl -LO https://raw.githubusercontent.com/Snoupix/pre-commit_upordawn/master/install_windows.bat
          .\install_windows.bat
          Remove-Item -Path "install_windows.bat"
  
      - name: Test hook
        run: |
          $ErrorActionPreference = "Continue"
          icacls .git/hooks/pre-commit.exe /grant Users:RX
          icacls .git/hooks/pre-commit.exe /grant Administrators:RX
          Start-Process -FilePath ".git/hooks/pre-commit.exe" -NoNewWindow -Wait
          $STATUS = $LASTEXITCODE
          $ErrorActionPreference = "Stop"
          if ($STATUS -ne 0 -and $STATUS -ne 2) {
              exit 1
          }

  # unix:
  #   runs-on: ${{ matrix.platform.os }}
  #   strategy:
  #     matrix:
  #       platform:
  #         - os: ubuntu-latest
  #         - os: macOS-latest
  #
  #   steps:
  #     - name: Cloning UpOrDawn repo
  #       uses: actions/checkout@v4
  #       with:
  #         repository: Snoupix/UpOrDawn
  #         ref: master
  #         token: ${{ secrets.TOKEN }}
  #      
  #     - name: Install hook
  #       run: |
  #         npm i -g prettier eslint
  #         sh -c "$(curl -Ls https://raw.githubusercontent.com/Snoupix/pre-commit_upordawn/master/install_unix.sh)"
  #
  #     - name: Test hook
  #       run: |
  #         set +e
  #         chmod +x .git/hooks/pre-commit
  #         ./.git/hooks/pre-commit
  #         STATUS=$?
  #         set -e
  #         if [[ $STATUS -ne 0 && $STATUS -ne 2 ]]; then exit 1; fi
