name: Testing pre-commit on every platform

on:
  push:
    branches:
      - '*test'

jobs:
  build:
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
          - os: ubuntu-latest
          - os: macOS-latest
          - os: windows-latest

    steps:
      - name: Clone UpOrDawn repo
        uses: actions/checkout@v4
        with:
          repository: Snoupix/UpOrDawn
          ref: master
          token: ${{ secrets.TOKEN }}
        
      - if: matrix.platform.os == 'windows-latest'
        name: Install hook
        run: |
          cd UpOrDawn
          ../install_windows.bat

      - if: matrix.platform.os != 'windows-latest'
        name: Install hook
        run: |
          cd UpOrDawn
          chmod +x ../install_unix.sh
          ../install_unix.sh

      # - name: Test install script
      #   run: |
      #     cd UpOrDawn
      #     if [ "${{ matrix.platform.os }}" == "windows-latest" ]; then
      #       ../install_windows.bat
      #     else
      #       chmod +x ../install_unix.sh
      #       ../install_unix.sh
      #     fi

      - name: Test hook
        run: |
          cd UpOrDawn
          git add .
          git commit -m "Test commit" # "echo $?" should be equal to 0
