name: Testing pre-commit on every platform

on:
  push:
    branches:
      - '*test'

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - name: Cloning UpOrDawn repo
        uses: actions/checkout@v4
        with:
          repository: Snoupix/UpOrDawn
          ref: master
          token: ${{ secrets.TOKEN }}

      - name: Cloning install script
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            install_windows.bat
          sparse-checkout-cone-mode: false
          path: script
        
      - name: Install hook
        run: |
          .\script\install_windows.bat

      - name: Test hook
        run: |
          echo "Test" > test_file.txt
          git config --global user.name "Snoupix"
          git config --global user.email "test@test.com"
          git add .
          git commit -m "Test commit" # "echo $?" should be equal to 0

  unix:
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
          - os: ubuntu-latest
          - os: macOS-latest

    steps:
      - name: Cloning UpOrDawn repo
        uses: actions/checkout@v4
        with:
          repository: Snoupix/UpOrDawn
          ref: master
          token: ${{ secrets.TOKEN }}

      - name: Cloning install script
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            install_unix.sh
          sparse-checkout-cone-mode: false
          path: script
        
      - name: Install hook
        run: |
          chmod +x ./script/install_unix.sh
          ./script/install_unix.sh

      # - name: Test install script
      #   run: |
      #     cd UpOrDawn
      #     if [ "${{ matrix.platform.os }}" == "windows-latest" ]; then
      #       ../install_windows.bat
      #     else
      #       chmod +x ../install_unix.sh
      #       ../install_unix.sh
      #     fi

      - name: Test hook
        run: |
          echo "Test" > test_file.txt
          git config --global user.name "Snoupix"
          git config --global user.email "test@test.com"
          git add .
          git commit -m "Test commit" # "echo $?" should be equal to 0
