name: Testing pre-commit on every platform

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
          - os: ubuntu-latest
          - os: macOS-latest
          - os: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Clone UpOrDawn repo
        run: |
          git clone https://github.com/Snoupix/UpOrDawn
        
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.platform.target }}
          override: true

      - name: Build hook
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--release"

      - if: matrix.platform.os == 'windows-latest'
        name: Install hook
        run: |
          cd UpOrDawn
          ../install_windows.bat

      - if: matrix.platform.os != 'windows-latest'
        name: Install hook
        run: |
          cd UpOrDawn
          chmod +x ../install_unix.sh
          ../install_unix.sh

      # - name: Test install script
      #   run: |
      #     cd UpOrDawn
      #     if [ "${{ matrix.platform.os }}" == "windows-latest" ]; then
      #       ../install_windows.bat
      #     else
      #       chmod +x ../install_unix.sh
      #       ../install_unix.sh
      #     fi

      - name: Test hook
        run: |
          cd UpOrDawn
          git add .
          git commit -m "Test commit" # "echo $?" should be equal to 0
